package com.test;

public class test10_8FortheBrands {
		public static void main(String[] args) {
			String duang = "忆捷（EAGET）         ,      "+
					"广博（GuangBo）                      ,      "+
					"希捷（SEAGATE）                      ,      "+
					"惠普（HP）                           ,      "+
					"信发（TRNFA）                        ,      "+
					"华为（HUAWEI）                       ,      "+
					"弓箭手（Arcarius）                   ,      "+
					"金士顿（Kingston）                   ,      "+
					"e代                                  ,      "+
					"天威（PrintRite）                    ,      "+
					"TOWE                                 ,      "+
					"爱普生（EPSON）                      ,      "+
					"西玛（SIMAA）                        ,      "+
					"现代（HYUNDAI）                      ,      "+
					"新贵（Newmen）                       ,      "+
					"安普网联（AMP NETCONNECT）           ,      "+
					"得力（deli）                         ,      "+
					"马培德（Maped）                      ,      "+
					"美商海盗船（USCORSAIR）              ,      "+
					"狼蛛（AULA）                         ,      "+
					"绿联（UGREEN）                       ,      "+
					"罗技（Logitech）                     ,      "+
					"佳能（Canon）                        ,      "+
					"普联（TP-LINK）                      ,      "+
					"胜为（shengwei）                     ,      "+
					"TANGO                                ,      "+
					"讯拓（Sunt）                         ,      "+
					"优派（ViewSonic）                    ,      "+
					"麦克赛尔（Maxell）                   ,      "+
					"齐心（COMIX）                        ,      "+
					"传美                                 ,      "+
					"权尚（Transshow）                    ,      "+
					"AUCS                                 ,      "+
					"富士施乐（Fuji Xerox）               ,      "+
					"铼德（RITEK）                        ,      "+
					"IT-CEO                               ,      "+
					"台电（TECLAST）                      ,      "+
					"优越者                               ,      "+
					"创见（Transcend）                    ,      "+
					"富勒（Fuhlen）                       ,      "+
					"英雄（HERO）                         ,      "+
					"格之格                               ,      "+
					"奥尼（aoni）                         ,      "+
					"华硕（ASUS）                         ,      "+
					"飞鱼星                               ,      "+
					"惠朗（huilang）                      ,      "+
					"金隆兴                               ,      "+
					"友讯（D-Link）                       ,      "+
					"山泽（SAMZHE）                       ,      "+
					"Canon                                ,      "+
					"艾泰（UTT）                          ,      "+
					"LaCie                                ,      "+
					"三堡（SMT）                          ,      "+
					"dostyle                              ,      "+
					"芬尚                                 ,      "+
					"达尔优                               ,      "+
					"思科（CISCO）                        ,      "+
					"小米（MI）                           ,      "+
					"秋叶原（CHOSEAL）                    ,      "+
					"良工（lengon）                       ,      "+
					"朗科（Netac）                        ,      "+
					"摩天手（Mofii）                      ,      "+
					"水星（MERCURY）                      ,      "+
					"清风（kyfen）                        ,      "+
					"白雪（snowhite）                     ,      "+
					"HAILE                                ,      "+
					"爱国者（aigo）                       ,      "+
					"飞利浦（PHILIPS）                    ,      "+
					"绿巨能（llano）                      ,      "+
					"联想（Lenovo）                       ,      "+
					"腾达（Tenda）                        ,      "+
					"汇东                                 ,      "+
					"迅捷（FAST）                         ,      "+
					"凯萨（KAISA）                        ,      "+
					"百旺                                 ,      "+
					"高品乐                               ,      "+
					"金球（Gold Ball）                    ,      "+
					"毕加索（pimio）                      ,      "+
					"雷蛇（Razer）                        ,      "+
					"得印（befon）                        ,      "+
					"宝克（BAOKE）                        ,      "+
					"富士通（Fujitsu）                    ,      "+
					"雷柏（Rapoo）                        ,      "+
					"奔图（PANTUM）                       ,      "+
					"奥速（ASHU）                         ,      "+
					"东芝（TOSHIBA）                      ,      "+
					"微软（Microsoft）                    ,      "+
					"莱盛                                 ,      "+
					"SHARP                                ,      "+
					"真彩（TRUECOLOR）                    ,      "+
					"双飞燕（A4TECH）                     ,      "+
					"英特曼（Etman）                      ,      "+
					"三木（SUNWOOD）                      ,      "+
					"晨光（M&G）                          ,      "+
					"施德楼（STAEDTLER）                  ,      "+
					"网件（NETGEAR）                      ,      "+
					"国誉（KOKUYO）                       ,      "+
					"联想                                 ,      "+
					"绘威                                 ,      "+
					"uni                                  ,      "+
					"金得利                               ,      "+
					"兄弟（brother）                      ,      "+
					"金河田（Golden field）               ,      "+
					"开博尔（Kaiboer）                    ,      "+
					"黑爵（AJAZZ）                        ,      "+
					"索尼（SONY）                         ,      "+
					"摩豹（Motospeed）                    ,      "+
					"卡西欧（CASIO）                      ,      "+
					"啄木鸟                               ,      "+
					"久好                                 ,      "+
					"埃特（elite_value）                  ,      "+
					"普霖                                 ,      "+
					"包尔星克（PowerSync）                ,      "+
					"卡文（KAWEN）                        ,      "+
					"探戈                                 ,      "+
					"欣乐（UPM Copykid）                  ,      "+
					"TEXAS INSTRUMENTS                    ,      "+
					"KODAK                                ,      "+
					"BROADLINK                            ,      "+
					"松下（Panasonic）                    ,      "+
					"公牛（BULL）                         ,      "+
					"B.O.W                                ,      "+
					"纽曼（Newsmy）                       ,      "+
					"磊科（netcore）                      ,      "+
					"施乐（XEROX）                        ,      "+
					"百乐（PILOT）                        ,      "+
					"罗技（G）                            ,      "+
					"宜客莱（ECOLA）                      ,      "+
					"华三（H3C）                          ,      "+
					"镭拓（Rantopad）                     ,      "+
					"派克（PARKER）                       ,      "+
					"登峰                                 ,      "+
					"奥睿科（ORICO）                      ,      "+
					"突破（TOP）                          ,      "+
					"CE-LINK                              ,      "+
					"三星（SAMSUNG）                      ,      "+
					"Panasonic                            ,      "+
					"赛睿（SteelSeries）                  ,      "+
					"闪迪（SanDisk）                      ,      "+
					"铭大金碟（MNDA）                     ,      "+
					"ZINWELL                              ,      "+
					"西部数据（WD）                       ,      "+
					"必联（B-LINK）                       ,      "+
					"马可（MARCO）                        ,      "+
					"金胜（kingshare）                    ,      "+
					"优和（UHOO）                         ,      "+
					"Double A                             ,      "+
					"盆景（bonsaii）                      ,      "+
					"绍泽文化（ShaoZe Culture）           ,      "+
					"飚王（SSK）                          ,      "+
					"RK                                   ,      "+
					"COMFAST                              ,      "+
					"ThinkPad                             ,      "+
					"映美（Jolimark）                     ,      "+
					"探戈（TANGO）                        ,      "+
					"Webetter                             ,      "+
					"CHERRY                               ,      "+
					"360                                  ,      "+
					"耐力（NIKO）                         ,      "+
					"E.T                                  ,      "+
					"紫光（UNIS）                         ,      "+
					"PNY                                  ,      "+
					"宜适酷（EXCO）                       ,      "+
					"OKI                                  ,      "+
					"DM                                   ,      "+
					"OV                                   ,      "+
					"奥普                                 ,      "+
					"赛德斯                               ,      "+
					"比比牛                               ,      "+
					"达善                                 ,      "+
					"埃普（UP）                           ,      "+
					"美的（Midea）                        ,      "+
					"多彩（Delux）                        ,      "+
					"领势（LINKSYS）                      ,      "+
					"睿因（Wavlink）                      ,      "+
					"毕亚兹（BIAZE）                      ,      "+
					"TOTOLINK                             ,      "+
					"技嘉（GIGABYTE）                     ,      "+
					"威迅（VENTION）                      ,      "+
					"鸿雁（HONYAR）                       ,      "+
					"影级（iNSIST）                       ,      "+
					"AOC                                  ,      "+
					"傲石                                 ,      "+
					"kinbor                               ,      "+
					"思印                                 ,      "+
					"钛度（Taidu）                        ,      "+
					"戴尔（DELL）                         ,      "+
					"樱花（SAKURA）                       ,      "+
					"北极熊（Polar bear）                 ,      "+
					"魔蛋（magicforce）                   ,      "+
					"Apple                                ,      "+
					"iQunix                               ,      "+
					"G.SKILL                              ,      "+
					"首席玩家（1st player）               ,      "+
					"游戏狂人（GAME MADMAN）              ,      "+
					"玛雅（MAYA）                         ,      "+
					"贝戋马户（james donkey）             ,      "+
					"新绿天章                             ,      "+
					"斐尔可                               ,      "+
					"铁威马（TERRA MASTER）               ,      "+
					"耐泊尔（NAIPOER）                    ,      "+
					"惠尔金                               ,      "+
					"明基（BenQ）                         ,      "+
					"banq                                 ,      "+
					"冰豹                                 ,      "+
					"晶华                                 ,      "+
					"麦沃（MAIWO）                        ,      "+
					"用友表单                             ,      "+
					"雷神（ThundeRobot）                  ,      "+
					"创享                                 ,      "+
					"普乐士                               ,      "+
					"辉柏嘉（Faber-castell）              ,      "+
					"绿奥                                 ,      "+
					"绘儿乐（Crayola）                    ,      "+
					"蚂蚁邦（Antbang）                    ,      "+
					"ikbc                                 ,      "+
					"NCL                                  ,      "+
					"品胜（PISEN）                        ,      "+
					"AKKO                                 ,      "+
					"Nakabayashi                          ,      "+
					"施耐德（Schneider）                  ,      "+
					"UBNT                                 ,      "+
					"埃森客（Ithink）                     ,      "+
					"翼蛇（yishe）                        ,      "+
					"优想                                 ,      "+
					"韩电（KEG）                          ,      "+
					"品恒（PIHEN）                        ,      "+
					"惠爱家                               ,      "+
					"谜石（MEGA STONE）                   ,      "+
					"N次贴（STICKN）                      ,      "+
					"纽曼（Newmine）                      ,      "+
					"极路由                               ,      "+
					"连盛                                 ,      "+
					"迪士尼（Disney）                     ,      "+
					"本手                                 ,      "+
					"菲森客（FTHINK）                     ,      "+
					"灵蛇                                 ,      "+
					"睿阜（REVOFREE）                     ,      "+
					"华擎（ASRock）                       ,      "+
					"吉选（GESOBYTE）                     ,      "+
					"飞兹（fizz）                         ,      "+
					"卡拉羊（Carany）                     ,      "+
					"安普康（AMPCOM）                     ,      "+
					"川宇                                 ,      "+
					"博扬（BOYANG）                       ,      "+
					"黑甲虫                               ,      "+
					"映美佳                               ,      "+
					"倍方                                 ,      "+
					"米家（MIJIA）                        ,      "+
					"天之（Tianzhi）                      ,      "+
					"RDS                                  ,      "+
					"iDiskk                               ,      "+
					"摩托罗拉（Motorola）                 ,      "+
					"Yottamaster                          ,      "+
					"富德                                 ,      "+
					"COOL-FISH                            ,      "+
					"魔炼者（MAGIC-REFINER）              ,      "+
					"大象键盘                             ,      "+
					"KONICA MINOLTA                       ,      "+
					"施耐德电气（Schneider Electric）     ,      "+
					"航嘉（Huntkey）                      ,      "+
					"正彩                                 ,      "+
					"菲沐（FAMOR）                        ,      "+
					"清华同方（THTF）                     ,      "+
					"青米（CHING MI）                     ,      "+
					"新科（Shinco）                       ,      "+
					"理光（Ricoh）                        ,      "+
					"威刚（ADATA）                        ,      "+
					"优蝶（YOUDIE）                       ,      "+
					"礼嘉（LIJIA）                        ,      "+
					"JASUN                                ,      "+
					"长城风行                             ,      "+
					"卓越佳印                             ,      "+
					"佳印                                 ,      "+
					"贝锐蒲公英                           ,      "+
					"富士樱（FUSICA）                     ,      "+
					"树德（Shuter）                       ,      "+
					"斯图（sitoo）                        ,      "+
					"精臣                                 ,      "+
					"MEMOBIRD                             ,      "+
					"KYOCERA                              ,      "+
					"DUKE                                 ,      "+
					"韧锋                                 ,      "+
					"JIB                                  ,      "+
					"東格                                 ,      "+
					"声缪斯（SONMUSE）                    ,      "+
					"外星人（Alienware）                  ,      "+
					"CABLE CREATION                       ,      "+
					"网易                                 ,      "+
					"缤乐美（papermate）                  ,      "+
					"子弹头                               ,      "+
					"海锚                                 ,      "+
					"SKW                                  ,      "+
					"一吉贝                               ,      "+
					"eKL                                  ,      "+
					"凌美（LAMY）                         ,      "+
					"3M                                   ,      "+
					"咪鼠科技（Mimouse）                  ,      "+
					"ON                                   ,      "+
					"乐多（OHTO）                         ,      "+
					"伟文（wewin）                        ,      "+
					"酷冷至尊（CoolerMaster）             ,      "+
					"雅文（Aria）                         ,      "+
					"传誉（Chuanyu）                      ,      "+
					"明瑞                                 ,      "+
					"天色（TIANSE）                       ,      "+
					"斑马牌（ZEBRA）                      ,      "+
					"晨鸣祥云                             ,      "+
					"金晨鸣                               ,      "+
					"晨鸣共好                             ,      "+
					"达而稳（DOREWIN）                    ,      "+
					"星遥博（Cinyobo）                    ,      "+
					"康铂（COMNPRO）                      ,      "+
					"大黄蜂（BUMBLEBEE）                  ,      "+
					"聚风                                 ,      "+
					"艾比格特（iBIG Stor）                ,      "+
					"沧田                                 ,      "+
					"新盟（Technology）                   ,      "+
					"M&G                                  ,      "+
					"ELFINBOOK                            ,      "+
					"锐意（Sharpie）                      ,      "+
					"炽魂（Blasoul）                      ,      "+
					"彩格                                 ,      "+
					"申士（SHEN SHI）                     ,      "+
					"欧标                                 ,      "+
					"战翼                                 ,      "+
					"迈拓（Maxtor）                       ,      "+
					"趁早                                 ,      "+
					"迪优美特（Diyomate）                 ,      "+
					"Campo Marzio Design                  ,      "+
					"富得快（FUDEKUAI）                   ,      "+
					"AZIO                                 ,      "+
					"大手印                               ,      "+
					"ifound                               ,      "+
					"至尚·创美（SCM）                     ,      "+
					"V4INK                                ,      "+
					"飞遁（LESAILES）                     ,      "+
					"雷霆世纪（Raytine）                  ,      "+
					"红环（rotring）                      ,      "+
					"铁修罗（TESORO）                     ,      "+
					"英菲克（INPHIC）                     ,      "+
					"奥卡斯（AUCAS）                      ,      "+
					"语鼠                                 ,      "+
					"金万年（Genvana）                    ,      "+
					"彩熙                                 ,      "+
					"雷腾                                 ,      "+
					"V’mo             ,"+
					"柯帅             ,"          +
					"蔺科             ,"          +
					"清风             ,"          +
					"赤度             ,"          +
					"微星（MSI）      ,"          +
					"TANOSEE          ,"          +
					"南国书香         ,"          +
					"猫太子（MAOTAIZI）"          +
					"得韵（DERWENT）  ,"          +
					"益而高（EaGLE）  ,"          +
					"前通（front）    ,"          +
					"isky             ,"          +
					"普贴（PUTY）     ,"          +
					"HELLBOY          ,"          +
					"爱快（iKuai）    ,"          +
					"兰科芯           ,"          +
					"纽赛（NUSIGN）   ,"          +
					"Tombow           ,"          +
					"LyfieEye         ,"          +
					"西玛             ,"          +
					"京造             ,"          +
					"CCB              ,"          +
					"爱立识           ,"          +
					"LEGRAND          ,"          +
					"宏碁（acer）     ,"          +
					"犀飞利（sheaffer）"          +
					"班图             ,"          +
					"双杰               ,         "+
					"开仰               ,         "+
					"灵逸               ,         "+
					"联众（UME）        ,         "+
					"梵想（FANXIANG）   ,         "+
					"ASV                ,         "+
					"茶花（CHAHUA）     ,         "+
					"指思（Jesis）      ,         "+
					"BUBM               ,         "+
					"杰思特（JEAST）    ,         "+
					"麦盘（bandisk）    ,         "+
					"百事泰（BESTEK）   ,         "+
					"派通（Pentel）     ,         "+
					"洛斐（LOFREE）     ,         "+
					"森松尼（sunsonny） ,         "+
					"武京生             ,         "+
					"天文（TEN-WIN）    ,         "+
					"蓝色妖姬（BLUELOVER,）       "+
					"舜普（SP）         ,         "+
					"硕方               ,         "+
					"airdisk            ,         "+
					"EG                 ,         "+
					"Cre8               ,         "+
					"未来世界                 ,          "+
					"金旗舰（GOLD FLAGSHIP）  ,          "+
					"新好                     ,          "+
					"暴享                     ,          "+
					"开玛（K-MARKING）        ,          "+
					"六品堂                   ,          "+
					"喵喵机                   ,          "+
					"科硕（KESU）             ,          "+
					"盖世小鸡（GAMESIR）      ,          "+
					"LD                       ,          "+
					"赛亿（SAIYI）            ,          "+
					"新北洋（SNBC）           ,          "+
					"H3C                      ,          "+
					"火派（FIREFACTION）      ,          "+
					"广颖电通（Silicon Power）,          "+
					"HP                       ,          "+
					"HANASS                   ,          "+
					"睿者易通（WITEASY）      ,          "+
					"博格利诺BOGELINUO        ,          "+
					"旗牌（Shachihata）       ,          "+
					"不得不爱                 ,          "+
					"飞利浦                   ,          "+
					"康亿（KONYEE）           ,          "+
					"德力西                   ,          "+
					"悦木（Joytop）              ,"         +
					"MOLESKINE                   ,"         +
					"安帝                        ,"         +
					"倪可（neecoo）              ,"         +
					"文谷（Wengu）               ,  "       +
					"ULO                         ,"         +
					"CHAINEDBOX                  , "        +
					"驰腾（chiteng）             ,         "+
					"SBARDA                      , "        +
					"京瓷（KYOCERA）             ,         "+
					"丽贴                        ,         "+
					"艾利                        ,         "+
					"星极（XANOVA）              ,    "     +
					"阿米洛（Varmilo）           ,   "      +
					"爱宝（Aibao）";
			String[] split = duang.split(",");
			for (int i = 0; i < split.length; i++) {
				System.out.println(split[i].replace(" ", ""));
			}
			
		}
}
